# make sure the configurations here are in alignment with your .env files

version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'swofdeath-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'jesus'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'christ'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3600:3306'
    expose:
      # Opens port 3600 on the container
      - '3600'
      # Where our data will be persisted
    volumes:
      - swofdeath-db-volume:/var/lib/mysql
# Names our volume
volumes:
  swofdeath-db-volume: