@startuml
title Use Case : get a list of all message shop (GET /api/shops)

box "Authentication & Authorization" #Lightblue
User -> Middleware : middleware(request)
Middleware -> Middleware : mustAuth(request)
alt 
Middleware -> jwtDecode : jwt_decode(token)
end alt
end box

Middleware -> NextRouter : GET(requestPathname, page_no, page_size)
NextRouter -> NextRouter : matchAPI(requestPathname)

box "API Handler"
NextRouter -> APIhandler : handler(req, res)

APIhandler -> PrismaClient : massageShop.findMany(searchParams)
database MYSQL
PrismaClient -> MYSQL : SELECT(searchParams)
MYSQL --> User : response(200, "successfully retrieved massage shops", massageShops)
end box

@enduml